### ISSUE TITLE
Erruer de l'image détat

### ISSUE THREAD

**Issue by bouillou7** [hbedek/Jeedom_docs#2]
![Screenshot 2021-10-01 at 16 06 26](https://user-images.githubusercontent.com/26858182/135633756-708be588-58c8-4157-8166-1cfb04fbf4f6.png)
bonjour, je viens d'acheter ton plugin et voilà l'état de mon widget, le retour d'état ne s'affiche pas

**Comment by hbedek** [comment]
Bonjour,

Tout d'abord merci d'avoir acheté le plugin.
Je vais récupérer quelques informations pour investiguer:
- Tu es en Béta / Stable ?
- Pourrais tu m'envoyer le résultat de la commande Etat ?
- Pourrais tu m'envoyer une photo de la config de ton équipement ?

Normalement cela devrait déjà me donner une bonne idée

**Comment by bouillou7** [comment]
Re,
Je suis en stable et voici les éléments que tu m'as demandé
![Screenshot 2021-10-01 at 16 44 04](https://user-images.githubusercontent.com/26858182/135639978-19d9b567-383d-40e1-b9ef-a0460e813b9a.png)
![Screenshot 2021-10-01 at 16 43 43](https://user-images.githubusercontent.com/26858182/135639983-37ce4309-bf0e-4d63-999d-de22965d3526.png)
.

**Comment by hbedek** [comment]
Je vois que tu n'as pas renseigné de capteur d'ouverture de porte.
Actuellement en Stable le capteur d'ouverture de porte est nécessaire pour le fonctionnement du plugin.

Si tu veux je suis en train de mettre en place une version light du plugin pour un fonctionnement sans capteur d'ouverture de porte, mais c'est actuellement en Béta

**Comment by bouillou7** [comment]
Je ne sais pas comment activer les bétas sur le market. 
J'attend mon capteur d'ouverture qui doit arriver d'ici 10-15 jours

**Comment by hbedek** [comment]
Pour activer les bétas, tu vas sur le market jeedom, puis sur ton profil.
De la tu peux cocher: Activer l'accès aux plugins beta.
![image](https://user-images.githubusercontent.com/84860573/135641203-c9be6d1a-179e-4d19-9c82-d6c1030f832e.png)

Si jamais tu as un problème avec la version sans capteur d'ouverture de porte, n'hésites pas à me faire une retour

**Comment by bouillou7** [comment]
Re,
J'ai reçu mon capteur pour la porte mais ça n'a pas l'air d'avoir fonctionner. Comme tu peux le voir sur la capture d'écran, la porte est ouvert mais sur ton plugin, elle reste fermée et quand je teste l'état, rien ne se passe
![Screenshot 2021-10-05 at 20 15 19](https://user-images.githubusercontent.com/26858182/136080126-67c3adb3-e2f6-4a46-b625-135d08cb6d90.png)
![Screenshot 2021-10-05 at 20 10 24](https://user-images.githubusercontent.com/26858182/136080138-2c5dc173-3fa9-40c1-82fa-f8ecab0510e7.png)
.

**Comment by hbedek** [comment]
Tu pourrais vérifier dans la configuration du plugin que le démon est bien démarré ?

**Comment by bouillou7** [comment]
![image](https://user-images.githubusercontent.com/26858182/136089910-694b57f9-ac12-48f0-9aae-fe6176f9d75f.jpeg)

J'ai relancé mais toujours la même

**Comment by hbedek** [comment]
Ok, mets toi en débug, ouvre la porte et envoie moi le log

**Comment by bouillou7** [comment]
Écoute. Dès que je l'ai passé en Debug, ça c'est mis à fonctionner. Je suis dessus depuis cet après-midi. 
Je viens de faire une dizaine de tests et ça fonctionne. 
Je vais laisser en Debug du coup.

**Comment by hbedek** [comment]
Ok tiens moi au courant si tu as un problème. Je vais clore le point sur github.
Si jamais tu as de nouveau un problème contacte moi plutôt sur Community, je reçois plus facilement les notifications.

Bonne utilisation
